name: sphinx-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install 
    - name: Build docs/ folder
      run: |
        poetry run sphinx-build docs/. docs/site
    - name: Push document to gh-pages
      run: |
        poetry run ghp-import docs/site --no-jekyll --push --force
    #   surprisingly ghp-import is able to back push to repo without extra help or credentials 
